FROM alpine:3.16.2

LABEL maintainer "Vadim Delendik <vdelendik@zebrunner.com>"

ENV DEBIAN_FRONTEND=noninteractive

#=============
# Set WORKDIR
#=============
WORKDIR /root

#==================
# General Packages
#==================
RUN apk add --no-cache \
    bash \
    openjdk17 \
    tzdata \
    curl \
    git \
    git-fast-import \
    openssh-client \
    bind-tools \
    gnupg \
    lsof && \
    rm -rf /var/lib/apt/lists/* /usr/lib/jvm/java-17-openjdk/demo /usr/lib/jvm/java-17-openjdk/man /usr/lib/jvm/java-17-openjdk/jre/demo /usr/lib/jvm/java-17-openjdk/jre/man

#===============
# Install Docker
#===============
RUN apk add --no-cache docker openrc \
    && rc-update add docker boot

#===============
# Set JAVA_HOME
#===============
ENV JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
ENV PATH=$PATH:$JAVA_HOME/bin

#======================
# Install Jenkins swarm
#======================
ENV JENKINS_SLAVE_ROOT="/opt/jenkins"

USER root

RUN mkdir -p "$JENKINS_SLAVE_ROOT"
RUN mkdir -p /opt/apk

# Slave settings
ENV JENKINS_MASTER_USERNAME="jenkins" \
    JENKINS_MASTER_PASSWORD="jenkins" \
    JENKINS_MASTER_URL="http://jenkins:8080/" \
    JENKINS_SLAVE_MODE="exclusive" \
    JENKINS_SLAVE_NAME="swarm-$RANDOM" \
    JENKINS_SLAVE_WORKERS="1" \
    JENKINS_SLAVE_LABELS="" \
    AVD="" \
    SWARM_RESPONSE_TIMEOUT=60

# Set the lang, you can also specify it as as environment variable through docker-compose.yml
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8\
    LC_ALL=en_US.UTF-8

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
