FROM jenkins/inbound-agent:latest-jdk11

LABEL maintainer "Vadim Delendik <vdelendik@zebrunner.com>"

ENV ADBKEY=
ENV ADBKEY_PUB=

ENV DEBIAN_FRONTEND=noninteractive

USER root

#=============
# Set WORKDIR
#=============
WORKDIR /root

#==================
# General Packages
#==================
RUN apt-get -qqy update && \
	apt-get -qqy --no-install-recommends install lsof android-tools-adb

USER ${user}

COPY files/zebrunner-jenkins-agent /usr/local/bin/zebrunner-jenkins-agent

WORKDIR /home/${user}
ENTRYPOINT ["zebrunner-jenkins-agent"]
