FROM jenkins/inbound-agent:latest-jdk17

LABEL maintainer "Vadim Delendik <vdelendik@zebrunner.com>"

ENV DEBIAN_FRONTEND=noninteractive

USER root

#=============
# Set WORKDIR
#=============
WORKDIR /root

#==================
# General Packages
#==================
RUN apt-get -qqy update && \
	apt-get -qqy --no-install-recommends install lsof android-tools-adb

USER ${user}

WORKDIR /home/${user}
ENTRYPOINT ["jenkins-agent"]
