#!/usr/bin/env sh

# Place adb private and public keys if any
if [ ! -z ${ADBKEY} ] && [ ! -z ${ADBKEY_PUB} ]; then
  mkdir ~/.android
  echo ${ADBKEY} > ~/.android/adbkey
  chmod 600 ~/.android/adbkey
  echo ${ADBKEY_PUB} > ~/.android/adbkey.pub
  chmod 644 ~/.android/adbkey.pub
fi

# launch default jnpl cmd
/usr/local/bin/jenkins-agent
